server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev?characterEncoding=utf-8&useUnicode=true&serverTimezone=GMT%2b8
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 400MB
      max-request-size: 400MB
mybatis:
  mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis的xml文件

#  这个导入mybatis 就不能用了
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台输出sql语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
files:
  upload:
    path: E:\BaiduNetdiskDownload\llll\abc\aa\upload\

